### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mRdzut** [Kevin0z0/Python_NetEaseMusicAPI#10]
使用/api/user/detail?uid=1354678570接口出现server 500的问题，可能接口出现了问题

**Comment by Kevin0z0** [comment]
测试了一下，我这边是没有问题的
![image](https://user-images.githubusercontent.com/24759492/124377446-8e1c4580-dcde-11eb-8b7a-23459444b70f.png)

**Comment by mRdzut** [comment]
![图片](https://user-images.githubusercontent.com/51366195/124377609-54980a00-dcdf-11eb-85b0-81880ec7598d.png)
本地的话依然是用不了

**Comment by Kevin0z0** [comment]
cookies里面的MUSIC_U需要有值，也就是需要登陆，但他不判断这个值是否正确，随便给一个就行

**Comment by Kevin0z0** [comment]
![image](https://user-images.githubusercontent.com/24759492/124377843-b9079900-dce0-11eb-8748-c4f9def8c4df.png)

**Comment by mRdzut** [comment]
请问具体是需要在哪个文件添加你所说的music_u,并没有在接口的代码里看到这个参数

**Comment by Kevin0z0** [comment]
登录接口直接登录就会自动生成的
