### ISSUE TITLE
登录请求时出现 "网络太拥挤，请稍后再试" 错误

### ISSUE THREAD

**Issue by LinGuohao** [Kevin0z0/Python_NetEaseMusicAPI#11]
我使用手机号密码登入 一开始成功登入 但是调用status接口返回301，因此我退出后重新登入得到：**网络太拥挤，请稍后再试**  错误 （间隔长时间后重试错误依然存在）
不知道如何解决

我在境外 是否受到影响？

http://127.0.0.1:8000/api/user/login?phone=186*****3134&password=******
```
{
    "code": -462,
    "data": {
        "actionCode": "1102401",
        "verifyType": 50,
        "verifyId": 1,
        "verifyUrl": "",
        "blockText": "网络太拥挤，请稍候再试。",
        "verifyToken": null,
        "btnText": null,
        "orpheusUrl": null,
        "frontRuleIds": [
            1102401
        ],
        "params": {
            "event_id": "00264373255162507283",
            "sign": "cb3ebfbee931c0fdc3bf6ac2f0ba2721"
        },
        "url": null
    },
    "message": "网络太拥挤，请稍候再试。"
}
```

**Comment by Kevin0z0** [comment]
账号密码现在可能已经需要验证滑块之后才能登了，我过几天加一个短信验证码登录吧

**Comment by LinGuohao** [comment]
不太清楚 但是我一开始调用是成功的 返回Result 200， 但是status接口依然301， 退出后重新登入就再也不行了

**Comment by Kevin0z0** [comment]
两年前的东西了，难免有些接口用不了😂

**Comment by Kevin0z0** [comment]
已更新，可以试试手机验证码登录 https://github.com/Kevin0z0/Python_NetEaseMusicAPI/blob/master/docs/user.md#使用验证码登录账号

**Comment by LinGuohao** [comment]
验证登录接口是啥 没看到api啊

**Comment by Kevin0z0** [comment]
加了忘记commit了😅 /api/user/cellphone?phone=&code=
