### ISSUE TITLE
eapi的加密方式是否需要更新？

### ISSUE THREAD

**Issue by tmsdy** [Kevin0z0/Python_NetEaseMusicAPI#4]
试了下修改歌单描述的接口：
http://127.0.0.1:8000/api/playlist/update/desc?id=5310******&desc=123123123
返回值是
{"msg":"作弊","code":250,"message":"作弊"}

**Comment by tmsdy** [comment]
是在登录成功后请求的，有cookie的

**Comment by tmsdy** [comment]
试了下nodejs的版本是可以的额
http://*********:3000/playlist/update/desc?id=53******&desc=123123123

返回值是
{"/api/playlist/tags/update":{"code":200},"/api/playlist/desc/update":{"code":200},"/api/playlist/update/name":{"code":200},"code":200}

**Comment by Kevin0z0** [comment]
已修复，感谢指出问题
